### ISSUE TITLE
能不能ipad和键盘一起用

### ISSUE THREAD

**Issue by Asiimoviet** [Sanheiii/Mageki#10]
我放了mu3input以后键盘上面的按键就失效了
有没有办法可以让ipad和键盘同时工作 我想要把ipad当成纯摇杆还有侧键

btw有没有想法开发一个纯摇杆版

**Comment by Sanheiii** [comment]
键盘输入是其他人写的io，并且暂时不能与我这边的mu3io同时使用

**Comment by Sanheiii** [comment]
听说有新版的mu3hook.dll内置了键盘操作,你可以去试试
