### ISSUE TITLE
在iOS上阅读FeliCa卡片 | Reading FeliCa cards on iOS

### ISSUE THREAD

**Issue by burritosoftware** [Sanheiii/Mageki#13]
你好，我看到阅读FeliCa卡的功能只限于安卓。但是，iOS也可以读取FeliCa卡。如果你看看App Store和GitHub上的SpiceCompanion的iOS版，它也可以读取Amusement IC/FeliCa卡。如果有可能的话，请将FeliCa卡的读取加入到iOS应用中。谢谢您!

Hi, I see that the ability to read FeliCa cards is limited to Android. However, iOS can also read FeliCa cards. If you look at the App Store and the iOS version of SpiceCompanion on GitHub, it can also read Amusement IC/FeliCa cards. If possible, please add FeliCa card reading to the iOS app. Thank you!

**Comment by Sanheiii** [comment]
This feature has been added to the todo list. Thanks for your advice!

**Comment by mxihan** [comment]
![4992WQM2YOL$V{PA2H1_HIN](https://user-images.githubusercontent.com/20372033/179367264-2062c700-7a61-4ae0-8915-ac3c8d5a7935.png)

**Comment by Sanheiii** [comment]
The latest version of Mageki already supports this feature, I will close this issue
