### ISSUE TITLE
ongeki-io中的mu3controller能否麻烦您去更新一下吗

### ISSUE THREAD

**Issue by FeiZhaixiage** [Sanheiii/Mageki#14]
我想制作ongeki小台，摇杆使用滑块电阻，目前能正常使用并且没有很大抖动和误差的只有ongeki-io的mu3controller，我看您在继续维护那个项目，如果您方便的话能否对其中的代码进行优化。
目前它缺少的支持：
1.  test，service按键
2.  无法连接新的io（1.1.0）【可能是我没设置好】
3.  无法正常刷卡

如果可以的话那真是帮大忙了，感谢您无私的付出。

**Comment by Sanheiii** [comment]
这一部分是geekidos的代码，他的手台没有test键和读卡器，同时按下两个menu键进入test，segatools.ini中的protocol设为hid连接到ongeki-io，同时按下两侧侧键刷卡

**Comment by Sanheiii** [comment]
要刷test分支的mu3controller

**Comment by FeiZhaixiage** [comment]
> 要刷test分支的mu3controller

我尝试去刷了test分支的mu3controller可是没有作用
原代码中只设置了两个menu键进行刷卡并且卡号只能是02FFFFFFFFFFFFFFFFFF
源代码：
```
if(data->buttons[4] && data->buttons[9]) {
    EEPROM.get(0, data->aimi_id);
    data->scan = true;
} else {
    memset(&data->aimi_id, 0, 10);
    data->scan = false;
}
```

![image](https://user-images.githubusercontent.com/42127557/168242107-ce814ba4-1aea-40bc-8e91-0e9ae3bd6e9c.png)

**Comment by Sanheiii** [comment]
抱歉是我记错了，mu3controller中目前没有test功能，只是test分支的io能接收test键，我维护io仅为了与移动设备链接，你可以自己在mu3controller中实现test并提交pr到https://github.com/GEEKiDoS/ongeki-io

**Comment by FeiZhaixiage** [comment]
好的，感谢您的回复。

**Comment by FeiZhaixiage** [comment]
已自行解决 https://github.com/FeiZhaixiage/mu3-controller
