### ISSUE TITLE
App connects to Test but no input in game

### ISSUE THREAD

**Issue by burritosoftware** [Sanheiii/Mageki#15]
Hi, I am testing this with bright memory, however it seems that Test.exe doesn't open when I run the game. If I open it manually, I see it can see the Aime card I am using in the game when I tap it using my keyboard, and I can also see it picking up my tablet's inputs, however nothing happens in game.

The logo does not turn black when the game is open, only when Test.exe is open.

Also, if you have chat like Discord or Twitter it would be nice if I could talk in a live setting

Using iPad (2021)

**Comment by Sanheiii** [comment]
I have sent a private message to you on discord

**Comment by burritosoftware** [comment]
> I have sent a private message to you on discord

I don't see it, you can join https://website.burrito.software/discord to get to my server

**Comment by Sanheiii** [comment]
I forgot to add mu3hook.dll to MU3Input_1.1.0.zip, now this issue is fixed.
