### ISSUE TITLE
aime check

### ISSUE THREAD

**Issue by KengHuai** [Sanheiii/Mageki#2]
等了20分钟还是在check，换成原文件直接秒check。
使用服务器aquav0.0.22c:

**Comment by Sanheiii** [comment]
把你现在用的segatools.ini贴出来看一下，今天看到挺多人都有这个问题的

**Comment by KengHuai** [comment]
[vfs]
amfs=amfs
option=D:\Ongeki Red+\Ongeki Red+\package\options
appdata=appdata

[aime]
enable=1
aimePath=DEVICE\aime.txt
felicaGen=0

[dns]
default=192.168.1.2

[netenv]
enable=1

[pcbid]

[keychip]
subnet=192.168.1.0
id=A88E-69A88888888

[io3]
mode=1

test=0x31
service=0x32

[dinput]
LEFT_A=0x46
LEFT_B=0x54
LEFT_C=0x47
LEFT_MENU=0x52
LEFT_SIDE=0x56
RIGHT_A=0x48
RIGHT_B=0x55
RIGHT_C=0x4A
RIGHT_MENU=0x49
RIGHT_SIDE=0x4E
SLIDER_LEFT=0x57
SLIDER_RIGHT=0x51
SLIDER_SPEED=1000

**Comment by Sanheiii** [comment]
可以把你整个游戏打包发来吗，我挨个替换文件看看问题所在

**Comment by KengHuai** [comment]
mu3hook.dll这个文件的问题我已经试过了

**Comment by Sanheiii** [comment]
> mu3hook.dll这个文件的问题我已经试过了

整个发来我挨个替换别的文件看看

**Comment by Sanheiii** [comment]
> mu3hook.dll这个文件的问题我已经试过了

关掉emoney看看,就在那几个config中

**Comment by Sanheiii** [comment]
> mu3hook.dll这个文件的问题我已经试过了

新版里我把几个配置文件一起打包了，你可以试试，如果能用的话回复一下我就关issue了

**Comment by KengHuai** [comment]
先经游戏，在检测网络就可以了。已经成功，顺带一提，bright也可以使用，完全没有问题。用的IPAD
