### ISSUE TITLE
Usbmux不能双连

### ISSUE THREAD

**Issue by fadai0528** [Sanheiii/Mageki#23]
这是我的配置{
  "IO": [
    {
      "Type": "Usbmux",
      "Param": 4355,
      "Part": "GamePlay, Menu"
    },
    {
      "Type": "Usbmux",
      "Param": 4354,
      "Part": "Aime"
    }
  ]
}

打开test后提示未经处理的异常:  System.TypeInitializationException: “MU3Input.Mu3IO”的类型初始值设定项引发异常。 ---> System.InvalidOperationException: 序列不包含任何匹配元素
   在 System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   在 MU3Input.UsbmuxIO.DeviceEventCallback(iDeviceEvent& e, IntPtr userData)
   在 iMobileDevice.iDevice.iDeviceNativeMethods.idevice_event_subscribe(iDeviceEventCallBack callback, IntPtr userData)
   在 MU3Input.UsbmuxIO..ctor(UInt16 remotePort)
   在 MU3Input.MixedIO.CreateIO(IOType type, JToken param)
   在 MU3Input.Mu3IO..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 MU3Input.Mu3IO.Init()
   在 Test.Program.Main(String[] args)

**Comment by Sanheiii** [comment]
我没有两台iOS设备来测试这个，可以在iPad使用All，长按设置按钮来刷卡，iPhone的NFC比较严格，即使能用也要长按再刷卡，比较麻烦，必需要用iPhone刷卡也可以试试使用UDP协议，现在同一网段下设置中输入PC的IP地址可以解决部分连不上的问题

**Comment by fadai0528** [comment]
其實是想要ipad 打按鍵iphone 打側鍵和搖桿，不過謝謝了
