### ISSUE TITLE
UDP 模式下启动 AM Daemon/mu3.exe 闪退

### ISSUE THREAD

**Issue by LittleYang0531** [Sanheiii/Mageki#26]
如题所示

在所有配置没有问题，使用你提供的 mu3tool.dll，不使用 MU3Input.dll 的情况下，mu3.exe 和 amdaemon.exe 均能正常启动。

在使用 MU3Input.dll 情况下，使用 tcp 模式连接 Mageki 客户端，mu3.exe 和 amdaemon.exe 也能正常启动进入游戏。

在使用 MU3Input.dll 情况下，使用 udp 模式连接 Mageki 客户端，直接管理员运行 start.bat 后，amdaemon.exe 加载 MU3Input.dll 时闪退，mu3.exe 卡在 `システムプロセス 启动中` 界面。

但当率先启动 amdaemon.exe 时，amdaemon.exe 正常运行，随后启动 mu3.exe 在同样的地方闪退，无法启动游戏。

请问有什么解决办法吗，谢谢。

Ongeki 版本: SDDT 1.45

**Comment by Steve0807** [comment]
您好

主要开发者不在，您的情况非常怪异，我还是建议优先选择TCP连接，因为UDP还是存在着极大延迟的。

对于此问题，我对您是从哪获取到的mu3tool.dll有点疑惑，因为我们并不分发此dll

**Comment by Steve0807** [comment]
您好

对于此问题

我的建议是使用2.0.0的老版本去尝试，看看情况是否会复现

或者使用纯洁的包体去配置，因为我不敢保证您的包有无修改实现逻辑等等

**Comment by Sanheiii** [comment]
你可以先测试IOConfig中UDP是否能正常工作，如果可以的话在命令行中运行amdaemon查看相关报错

**Comment by LittleYang0531** [comment]
感谢回复。

我是从 ongeki-io 的 Release 界面下载的 MU3Input.zip，解压后用其 mu3tool.dll 覆盖了 package 目录下原生的 mu3tool.dll。

使用 ongeki-io 2.0.0 版本尝试后，发现日志输出多出一行，但对运行结果没有任何影响。

```bash
CLR:(C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll) Rejecting native image because native image dependency C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
```

回到 3.0.1，在 IOConfig 中使用 UDP 连接 Mageki，IOConfig 显示已连接，Mageki 中按下按键在 IOConfig 中均有反应。

这次我尝试使用管理员的 Powershell 运行程序，得到的日志文件如下:

```bash
--- Begin mu3_pre_startup ---
DVD: hook enabled.
Ongeki IO: Using custom IO DLL: MU3Input.dll
```

然后 amdaemon.exe 闪退，游戏卡死。

我是从 1cc 的 Discord 社区里提供的 pixeldrain 链接下载的游戏，不知道是否是这个包的问题。🤔

**Comment by LittleYang0531** [comment]
目前我可以通过 TCP 有线连接游玩

实在解决不了的话就算了吧

**Comment by Steve0807** [comment]
您好

因为此现象样本数过少，或者说您大概率真的为首例出现此情况的用户。

并且没有详细的调试日志，或者其他人可以复现此情况。

我建议您优先排查包，并且保证在包正常的情况下再次尝试配置mageki。

我暂时将此标记为Wont fix

**Comment by Codaaaaaa** [comment]
> 目前我可以通过 TCP 有线连接游玩
> 
> 实在解决不了的话就算了吧

同样amdaemon.exe闪退，也是pixeldrain上下载的。换成百度网盘后解决了
