### ISSUE TITLE
IOConfig.exe无响应

### ISSUE THREAD

**Issue by Chilor233** [Sanheiii/Mageki#27]
如题，IOConfig.exe打开之后无响应且不显示任何内容，一段时间后闪退。
![屏幕截图 2024-10-16 223006](https://github.com/user-attachments/assets/bbe7f2ab-d387-48c1-b515-22ddd74301c9)

**Comment by Chilor233** [comment]
> 您好
> 
> 请尝试重新安装适用于您的系统的 [MSIX可再发行组件](https://aka.ms/windowsappsdk/1.5/1.5.240802000/Microsoft.WindowsAppRuntime.Redist.1.5.zip)，这可能有助于您解决此问题
> 
> 或者您可以前往release页面使用2.0.x版本的mageki尝试

我在此之前已经因为提示需要runtime重新安装了#25 中提供的4个appx文件，但是打开后就出现了该问题，所以我觉得这可能不是runtime导致的问题

**Comment by Sanheiii** [comment]
首先尝试删除mu3input_config.json

**Comment by Chilor233** [comment]
> 首先尝试删除mu3input_config.json

感谢，问题已解决
