### ISSUE TITLE
IOConfig.exe并不会修改mu3input_config.json

### ISSUE THREAD

**Issue by fenglongmeier** [Sanheiii/Mageki#28]
我在IOConfig.exe内添加tcp通道或键盘之后，并不会被保存，并且在重新进入IOConfig.exe之后就会重置回之前的样子，所以修改始终不会生效，有什么可以尝试的解决办法吗？

**Comment by Sanheiii** [comment]
3.0.2打包出bug了，不过这个版本的更新都在MU3Input上，换成3.0.1的IOConfig就好
