### ISSUE TITLE
I can't run game if use MU3Input.dll included in ongeki-io

### ISSUE THREAD

**Issue by PruChan** [Sanheiii/Mageki#29]
If i don't use MU3Input.dll, the game will run normally, but the moment edit segatools.ini to specify the path to MU3Input.dll, the game will not run.
I attached some pictures

![image](https://github.com/user-attachments/assets/c59a8a7d-ee64-4cde-8291-820fcbb46d88)
I will not use MU3Input.dll, the game will run without any problems by passing through the 'システムプロセス' entry normally.

![image](https://github.com/user-attachments/assets/b935956e-f10b-436a-a94d-93eb008d30da)
![image](https://github.com/user-attachments/assets/204df9ab-71ef-467a-87a1-82068b43116e)
When load MU3Input.dll, the game no longer progresses beyond 'システムプロセス'

Is there anything I missed?
Overwriting the files in configs.zip but I did not solve the problem.
If load ongeki-io version 2.0.0 of dll, it runs normally, but I couldn't use the controller because it's an older version.
I tried everything all over again and changed the ongeki-io version and kept trying, but it didn't work out..
Game versions I tried were SDDT 1.45 and SDDT 1.39

**Comment by Sanheiii** [comment]
I think this issue may be caused by differences in the AMDaemon version. When my AMDaemon starts running, it outputs its version number. The absence of a version number in your screenshot may indicate that it’s not running, or that you’re using a different version than I am.
![图片](https://github.com/user-attachments/assets/bc1cc2e0-3124-45ce-82db-7cfe76cd654d)

**Comment by PruChan** [comment]
Is there any action I can take?
Even though the game is running fine, but I can't see the version of AMDaemon in my logs.

![image](https://github.com/user-attachments/assets/f032c214-c4ce-4582-855d-623cf4130c44)

**Comment by Sanheiii** [comment]
Could you provide a copy of your package folder? Please exclude its subfolders to reduce the file size.

**Comment by PruChan** [comment]
[package.zip](https://github.com/user-attachments/files/17566162/package.zip)
yes, I attached the file.

**Comment by Sanheiii** [comment]
I'm sorry, but I can't help you with this. I used your package to start AMDaemon and then launched the game, and I didn't encounter this issue.

**Comment by PruChan** [comment]
Ok thank you, I'll try running it on another PC
So I think it's probably a system environment issue, not a file issue.
But I don't understand why the problem doesn't occur with ongeki-io 2.0.0

**Comment by PruChan** [comment]
I finally solved this problem after 3 days..
This symptom occurred the same when running on another PC and it was related to a network conflict.
To fix this, It must need to completely remove all wireless connections except the wired connection in IOConfig. (I didn't remove the wireless connection even when I was wired.)
Can you please add a solution to the user manual for people who have encountered similar situations as me?

**Comment by Steve0807** [comment]
Hello

Thank you for your feedback. 

Your issue has been added to the User-Reported Issues section of the wiki.

[User-Reported Issues](https://github.com/Sanheiii/Mageki/wiki/Mageki-User-Manual#user-reported-issues-unverified)
