### ISSUE TITLE
Bright中摇杆无效

### ISSUE THREAD

**Issue by Reabin** [Sanheiii/Mageki#3]
其他按键都没问题，只有摇杆没有反应，用的是1.30原生文件

**Comment by Sanheiii** [comment]
在logo上滑动能不能动，用键鼠io的时候摇杆能动吗

**Comment by Reabin** [comment]
> 在logo上滑动能不能动，用键鼠io的时候摇杆能动吗

io测试那里摇杆是没问题的，键鼠io试了一下摇杆也没有反应

**Comment by Sanheiii** [comment]
> > 在logo上滑动能不能动，用键鼠io的时候摇杆能动吗
> 
> io测试那里摇杆是没问题的，键鼠io试了一下摇杆也没有反应

进test里面设置摇杆范围

**Comment by Reabin** [comment]
> > > 在logo上滑动能不能动，用键鼠io的时候摇杆能动吗
> > 
> > 
> > io测试那里摇杆是没问题的，键鼠io试了一下摇杆也没有反应
> 
> 进test里面设置摇杆范围

有这个选项吗，能否发一下假名

**Comment by Sanheiii** [comment]
> > > > 在logo上滑动能不能动，用键鼠io的时候摇杆能动吗
> > > 
> > > 
> > > io测试那里摇杆是没问题的，键鼠io试了一下摇杆也没有反应
> > 
> > 
> > 进test里面设置摇杆范围
> 
> 有这个选项吗，能否发一下假名

レバー 什么的，进去以后滑到最左边然后滑到最右边，就行了

**Comment by Sanheiii** [comment]
可以的话回复一下，我就关issue了
