### ISSUE TITLE
Not responding input

### ISSUE THREAD

**Issue by QuangduyGD** [Sanheiii/Mageki#30]
(https://github.com/user-attachments/assets/0495a3b7-1c0a-4145-8678-605f9db9836b)

Heres a footage(i only have my phone)

I have been trying to connect Ongeki with my Android phone via Mageki, it is connected but there's no response when I try to press the buttons(the buttons glowed up so I wonder whats causing this)

I have tried to copy config folder into package but it also doesn't seem to work well

I am running on 1.45B, Mageki 2.1.6 and Mu3 3.0.2

I don't include aime.io since holding down settings doesn't work so I use my Enter button to scan the card

**Comment by Steve0807** [comment]
Hello,

The main developer is currently offline.

For this issue, I suggest you overwrite the mu3hook.dll and MU3Input.dll files in the package folder to your game folder.

For the [aimeio], I believe it will be fixed as well after overwriting these files.

**Comment by Steve0807** [comment]
I also recommend you to checking that the "作用域" in the io_config.exe is set to "ALL".

**Comment by QuangduyGD** [comment]
I see, thanks
Will see if it works
