### ISSUE TITLE
添加path = MU3Input.dll无法正常启动游戏

### ISSUE THREAD

**Issue by Alvter** [Sanheiii/Mageki#31]
![image](https://github.com/user-attachments/assets/feefb48b-6008-48b3-a546-111a3249b4ab)
![image](https://github.com/user-attachments/assets/75e981dc-8689-420a-8ae8-a6bee5727660)
![image](https://github.com/user-attachments/assets/06ab9824-00eb-4251-8611-139d441204ec)
q启动后会直接跳到结束界面，如果注释path=MU3Input.dll则可以正常启动

**Comment by Sanheiii** [comment]
首先确认IOConfig是否可以打开并确认按键是否有效
打不开且没有提示->下载[最新版IO](https://github.com/Sanheiii/ongeki-io/releases/latest)
提示This application requires the Windows App Runtime->解决方法(https://github.com/Sanheiii/Mageki/issues/25)
成功打开且且按键正常->删除无线连接再尝试打开游戏

**Comment by Alvter** [comment]
删除tcp设备重新新建并连接可以进游戏了，但是有个新问题
IOConfig上可以正常同步手机虚拟按键，但是在游戏中没有反应

**Comment by Sanheiii** [comment]
关掉IOConfig再开游戏
