### ISSUE TITLE
Mu3hook相关问题

### ISSUE THREAD

**Issue by Nosty72** [Sanheiii/Mageki#4]
mu3hook.dll替换后debug启动后立即闪退，游戏也卡启动（一直显示启动中）；不换的话就没有问题

**Comment by Sanheiii** [comment]
> mu3hook.dll替换后debug启动后立即闪退，游戏也卡启动（一直显示启动中）；不换的话就没有问题

直接启动TestSharp.exe会不会闪退

**Comment by Nosty72** [comment]
也会

**Comment by Sanheiii** [comment]
> 也会

在cmd里跑应该会显示错误，发来看看

**Comment by Nosty72** [comment]
没有显示错误直接跳到了下一行。

对比了一下，好像我和那位同样发布了1.30 bright的人遇到的问题似乎一模一样，我也是用1.30的bright版本然后在替换dll后debug崩溃，卡在启动界面，双击testsharp也直接闪退

**Comment by People-11** [comment]
https://github.com/Sanheiii/Mageki/issues/6

**Comment by People-11** [comment]
https://github.com/Sanheiii/Mageki/issues/6

**Comment by Sanheiii** [comment]
> 没有显示错误直接跳到了下一行。
> 
> 对比了一下，好像我和那位同样发布了1.30 bright的人遇到的问题似乎一模一样，我也是用1.30的bright版本然后在替换dll后debug崩溃，卡在启动界面，双击testsharp也直接闪退

> #6

有没有安装.net framework 4.7的环境，处理器是不是x64的

**Comment by Nosty72** [comment]
已安装net framework 4.7，是x64

**Comment by Nosty72** [comment]
反馈

> 已安装net framework 4.7，是x64

反馈：安装了4.8以后debug问题已解决，成功连上mageki，卡启动的问题仍有

**Comment by Sanheiii** [comment]
> 反馈
> 
> > 已安装net framework 4.7，是x64
> 
> 反馈：安装了4.8以后debug问题已解决，成功连上mageki，卡启动的问题仍有

打开游戏的时候有没有debug窗口

**Comment by Nosty72** [comment]
有的

**Comment by Sanheiii** [comment]
> 有的

把segatools.ini里[mu3io]下面的内容删掉看看，还卡启动可以试试我的配置文件，我的mu3hook版本很新，有的包里带旧版升级可能配置不兼容

**Comment by Nosty72** [comment]
启动问题已解决，但是网络认证那边好像不行，一直显示BAD

**Comment by Sanheiii** [comment]
> 启动问题已解决，但是网络认证那边好像不行，一直显示BAD

检查一下segatools.ini里填的地址

**Comment by Nosty72** [comment]
感谢大佬指点，已经全部可以了🌷🌷
