### ISSUE TITLE
iOS bug for 1.0.1

### ISSUE THREAD

**Issue by KengHuai** [Sanheiii/Mageki#5]

**Comment by KengHuai** [comment]
{
  "DeviceInfo": {
    "DeviceType": "Physical",
    "Idiom": "Tablet",
    "Manufacturer": "Apple",
    "Model": "iPad11,3",
    "Name": "坑坏的iPad",
    "Platform": "iOS",
    "PlatFormVersion": "15.2",
    "ApplicationVersion": "1.0.1"
  },
  "Exception": "System.Collections.Generic.KeyNotFoundException: The given key '4450195664' was not present in the dictionary.\n  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) <0x10157a450 + 0x000a7> 673 in <25bf495f7d6b4944aa395b3ab5293479#117bdd1fd9889a0a62903209385e34a5>:0 \n  at Mageki.ControllerPanel.TouchEffect_TouchAction (System.Object sender, Mageki.TouchTracking.TouchActionEventArgs args) <0x101554ad0 + 0x0091b> in <001d06778ccd4264bdfbbbcb8f2e9326#117bdd1fd9889a0a62903209385e34a5>:0 \n  at Mageki.TouchTracking.TouchEffect.OnTouchAction (Xamarin.Forms.Element element, Mageki.TouchTracking.TouchActionEventArgs args) <0x101566520 + 0x0003b> in <001d06778ccd4264bdfbbbcb8f2e9326#117bdd1fd9889a0a62903209385e34a5>:0 \n  at Mageki.iOS.TouchRecognizer.FireEvent (Mageki.iOS.TouchRecognizer recognizer, System.Int64 id, Mageki.TouchTracking.TouchActionType actionType, UIKit.UITouch touch, System.Boolean isInContact) <0x100271830 + 0x0019b> in <6d22f8c4c8c14bd69d01eca77c65223b#117bdd1fd9889a0a62903209385e34a5>:0 \n  at Mageki.iOS.TouchRecognizer.TouchesMoved (Foundation.NSSet touches, UIKit.UIEvent evt) <0x100270f00 + 0x000e7> in <6d22f8c4c8c14bd69d01eca77c65223b#117bdd1fd9889a0a62903209385e34a5>:0 \n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) <0x1011af0e0 + 0x000ef> in <7a25fbab2bab4f9fb861eff5e989f7ae#117bdd1fd9889a0a62903209385e34a5>:0 \n  at Mageki.iOS.Application.Main (System.String[] args) <0x100270700 + 0x00027> in <6d22f8c4c8c14bd69d01eca77c65223b#117bdd1fd9889a0a62903209385e34a5>:0 "
}

**Comment by Sanheiii** [comment]
已修复，新版本发布前可以打开引导式访问缓解这个问题

**Comment by asps1726** [comment]
> 已修复，新版本发布前可以打开引导式访问缓解这个问题

ipad pro（ios 15.1）开了还是崩溃，好像在多压的情况下比较容易发生

**Comment by Sanheiii** [comment]
> > 已修复，新版本发布前可以打开引导式访问缓解这个问题
> 
> ipad pro（ios 15.1）开了还是崩溃，好像在多压的情况下比较容易发生
那先用旧版吧，再改改就发新版
