### ISSUE TITLE
bug for support on Ver 1.30

### ISSUE THREAD

**Issue by RealLinusZhang** [Sanheiii/Mageki#6]
mageki在red plus(1.25)上运行良好，但换了1.30的bright的hdd后用原版dll可以打开（键鼠操作），替换mageki的dll后打开及闪退(v1.0.0 v1.0.1均闪退)，闪一下ongeki io debug的窗口就崩溃推出了，无任何报错信息，直接卡systemprocess启动中。
设备：iPad Pro 10.5 + Mageki

**Comment by RealLinusZhang** [comment]
补充：直接打开testsharp也闪退

**Comment by Sanheiii** [comment]
#4
