### ISSUE TITLE
刷卡问题

### ISSUE THREAD

**Issue by Yukiyukina** [Sanheiii/Mageki#9]
{
  "DeviceInfo": {
    "DeviceType": "Physical",
    "Idiom": "Phone",
    "Manufacturer": "Xiaomi",
    "Model": "M2102K1C",
    "Name": "M2102K1C",
    "Platform": "Android",
    "PlatFormVersion": "12.0",
    "ApplicationVersion": "1.0.2"
  },
  "Exception": "Java.IO.IOException: Exception of type 'Java.IO.IOException' was thrown.\n  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <bf1fc8fa4fad451eb22285c832093052>:0 \n  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <bf1fc8fa4fad451eb22285c832093052>:0 \n  at Android.Nfc.Tech.NfcF.Connect () [0x0000a] in <615ece03fe8d49d09795325590e7cdb5>:0 \n  at Mageki.Droid.MainActivity.ProcessActionTechDiscoveredIntent (Android.Content.Intent intent) [0x00041] in <c022475b9ee049ce8a6a8b753c611ab6>:0 \n  at Mageki.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0005f] in <c022475b9ee049ce8a6a8b753c611ab6>:0 \n  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <615ece03fe8d49d09795325590e7cdb5>:0 \n  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)\n  --- End of managed Java.IO.IOException stack trace ---\njava.io.IOException\n\tat android.nfc.tech.BasicTagTechnology.connect(BasicTagTechnology.java:88)\n\tat android.nfc.tech.NfcF.connect(NfcF.java:37)\n\tat crc64b2aec2379c400bde.MainActivity.n_onCreate(Native Method)\n\tat crc64b2aec2379c400bde.MainActivity.onCreate(MainActivity.java:42)\n\tat android.app.Activity.performCreate(Activity.java:8238)\n\tat android.app.Activity.performCreate(Activity.java:8206)\n\tat android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3893)\n\tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)\n\tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)\n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loopOnce(Looper.java:210)\n\tat android.os.Looper.loop(Looper.java:299)\n\tat android.app.ActivityThread.main(ActivityThread.java:8085)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)\n"
}

**Comment by Sanheiii** [comment]
在设置中打开Mageki的NFC权限
